### ISSUE TITLE
VS Code -- emmet 2.0 -- syntax, placeholders, tabstops, ${cursor}, | , $0, $1, $2, etc.

### ISSUE THREAD

**Issue by user3323** [emmetio/css-snippets-resolver#3]
Damn.. There are so many problems with all these $1, $2, $0, ${}, | , ${cursor}, etc...
No offence, but it seems like the keystone method of their work is Math.random()  😐

Well, here are some bugs, that I found:

---------------
---------------

 the vertical symbol  `| ` (that should be responsible for the caret position after snippet expansion)

in the beginning of the value:

![image](https://user-images.githubusercontent.com/24613274/29999347-91597092-904d-11e7-8127-a317f9fe0b69.png)

makes this snippet disappear

![image](https://user-images.githubusercontent.com/24613274/29999351-b082be92-904d-11e7-896e-adc966ae95db.png)

---------------
---------------

and at the same time everything OK, when we put this symbol | - to the end of snippet:
![image](https://user-images.githubusercontent.com/24613274/29999407-cfd4e1ec-904f-11e7-9db8-eca30fae63c0.png)

:arrow_down: 

![image](https://user-images.githubusercontent.com/24613274/29999403-afc730ee-904f-11e7-8202-18ba0f5e6008.png)

---------------
---------------

if we put it in the property:

![image](https://user-images.githubusercontent.com/24613274/29999839-bd162b50-905f-11e7-9594-d9aa465bbb19.png)

it goes out as is:

![image](https://user-images.githubusercontent.com/24613274/29999848-e29dcd24-905f-11e7-9466-1164f994222c.png)

or in the property and in the value:

![image](https://user-images.githubusercontent.com/24613274/29999863-31495d12-9060-11e7-8be1-2d8f157d8032.png)

as is:

![image](https://user-images.githubusercontent.com/24613274/29999867-4568e754-9060-11e7-8abc-d656607e4dc0.png)

---------------
---------------

if it will be in the middle of the value - it would chop off a half of it:

![image](https://user-images.githubusercontent.com/24613274/29999480-60c992da-9053-11e7-9d30-58715f4f6981.png)

:arrow_down: 

![image](https://user-images.githubusercontent.com/24613274/29999483-6e183068-9053-11e7-9373-f7aa187aec22.png)

---------------
---------------

https://docs.emmet.io/customization/snippets/ says:

![image](https://user-images.githubusercontent.com/24613274/29999519-61bbbb0e-9054-11e7-8e90-4e15dbaef629.png)

> ... **${cursor}** or | are synonyms to $0 and used as caret position in generated output.

OK, let's check the `${cursor}` thing...

![image](https://user-images.githubusercontent.com/24613274/29999539-cb752ad4-9055-11e7-91fa-9970e05817bc.png)

... at the first glance:
![image](https://user-images.githubusercontent.com/24613274/29999542-fd1d043a-9055-11e7-8bf5-255c387545a3.png)

... and then 
![image](https://user-images.githubusercontent.com/24613274/29999544-24481004-9056-11e7-8d2c-1899ad27afe5.png)

So, no placeholder where we put it, nothing happened. (_and BTW no focus on the "none", bug from here https://github.com/emmetio/css-snippets-resolver/issues/2 is "fixed" :smile:_)

---------------
---------------

well, actually no matter what you will write in the curly braces, cursor, or something else:

![image](https://user-images.githubusercontent.com/24613274/29999580-fd18e264-9056-11e7-8b03-4a80f12cec34.png)
will give the same effect - nothing will happen:

![image](https://user-images.githubusercontent.com/24613274/29999544-24481004-9056-11e7-8d2c-1899ad27afe5.png)

---------------
---------------

$0 $1  -  in the property
$2       - in the value

![image](https://user-images.githubusercontent.com/24613274/29999642-437964e8-9059-11e7-9a57-c4f9259d6280.png)

almost everything is fine:

![lsn 0 1 2](https://user-images.githubusercontent.com/24613274/29999637-2af5f4d6-9059-11e7-9b19-3fe26d9c2501.gif)

why almost? there is no semicolon in the end.

@ramya-rao-a, btw is that ok, that emmet's snippets syntax about $0 (the first placeholder) goes upstream against VS Code snippets syntax, where $0 - the final placeholder? It makes a little confusion.

---------------
---------------

$0 $1   -  in the property

![image](https://user-images.githubusercontent.com/24613274/29999726-08597e54-905c-11e7-987f-082145dbfc45.png)

the same as above... placeholders works fine, and no semicolon in the end

![image](https://user-images.githubusercontent.com/24613274/29999736-66e20c52-905c-11e7-8db1-9ef4875ae6e9.png)

---------------
---------------

but, if we will try to put a placeholder just in the value
$0  -  in the value

![image](https://user-images.githubusercontent.com/24613274/29999760-3dd82f16-905d-11e7-9258-25d1dfbbe5a3.png)

emmet will output it as is:

![image](https://user-images.githubusercontent.com/24613274/29999775-591e205a-905d-11e7-8045-dc04d2e33d22.png)

... with semicolon in the end

---------------
---------------

and if zero would be wrapped in curly braces, it will work as it should:

![image](https://user-images.githubusercontent.com/24613274/29999786-d203995a-905d-11e7-9776-42457375f517.png)

![image](https://user-images.githubusercontent.com/24613274/29999796-0993a946-905e-11e7-8223-756590f34b4a.png)

---------------
---------------

And one more thing - about mentioned semicolons.
The good old emmet module, as I remember, was absorbing semicolon in the end of user's custom snippets, if there was one.
The new emmet (ver 2.0) does not. It just adds one more.

so this:
![image](https://user-images.githubusercontent.com/24613274/29999907-aedc9a22-9061-11e7-8a6c-5616c62f56c7.png)

becomes this:
![image](https://user-images.githubusercontent.com/24613274/29999923-47537960-9062-11e7-978e-f7369ddfacb0.png)

---------------
---------------

**Comment by ramya-rao-a** [comment]
**Caret position**

Use `${0}` as per Textmate snippet syntax. I don't believe Emmet 2.0 supports the `|` or `$cursor`

**Text inside ${....} disappearing**

As per text mate syntax, this gets treated as a snippet variable. Since there are no values defined for those variables inside Emmet 2.0 they get replaced with empty string

**Using multiple tab stops results in the one defined as ${0} to be the first one instead if the final one**

This is definitely a bug in the css-snippet-resolver module. When you have a snippet like 
`"lsn": "hello ${0} there${1} ok ${2}"`, the resolved snippet turns out as `hello ${1} there${2} ok ${3}`

To be Continued...

**Comment by ramya-rao-a** [comment]
** $0 $1 in property name resulting in missing ;**

Taking your example of `"lsn": "li$0st-st$1yle: none"`. In this case `li$0st-st$1yle` isn't deemed a valid property and so the snippet gets treated as simple text rather than a property-value pair. If it were identified as valid property, then you would have gotten the `;` at the end. See https://github.com/emmetio/css-snippets-resolver/blob/master/index.js#L64

This can be avoided if when checking whether snippet is a property, the $0, $1 were ignored. That I will leave to @sergeche  to decide

**Double semicolon**
The idea here I believe was not to have user add the `;`. Based on the syntax (css vs sass vs less vs stylus etc) and the customizations of `css/sass/stylus.propertyEnd` via `emmet.preferences`, the Emmet 2.0 adds the right ending.

Now should Emmet 2.0 be as forgiving as old emmet and absorb the extra semi-colon, I'll let @sergeche decide.

**Comment by ramya-rao-a** [comment]
Now, given all of the above, one pattern that emerges is that not all of the existing documentation for emmet in https://emmet.io does applies to Emmet 2.0

We need to come up with a good plan to give users a source of truth.

Since VS Code is the only editor at the moment using Emmet 2.0, I guess the onus falls on us.
I'll work on updating https://code.visualstudio.com/docs/editor/emmet with all of the information on custom snippets and how it differs from the old Emmet.

@sergeche If we can have link from your website to the vscode doc saying something like "If you are using VS Code, then you are using Emmet 2.0 and most of the below doesn't apply. Please read... ", that can be helpful

**Comment by user3323** [comment]
@ramya-rao-a , here is one more thing. About the devil, that's hiding in annoying details :)

basic emmet snippet expansion for `"content"` looks like this:
![image](https://user-images.githubusercontent.com/24613274/30004868-3e89bb28-90df-11e7-961d-030db5910a8d.png)

with tabstop in the quotemarks and NO tabstop in the end.
so user should cllick at the end of the line, or find key "End" on the keyboard. 
too many movements!

I decided to create my custom snippet:
`"cn": "content: '${0}'${1}"`

![content tabstops](https://user-images.githubusercontent.com/24613274/30004906-cffcc028-90df-11e7-8d2e-4ccfeff15abc.gif)

and this second tabstop, as you see, goes BEFORE semicolon
so the question is - how can user make tabstop appear AFTER the semicolon?

So my point is, that every basic and custom emmet snippet must have a final tabstop by default in the end (after semicolon), no matter would it be the only one, or would it be 2nd, 3rd, etc.

**Comment by ramya-rao-a** [comment]
> every basic and custom emmet snippet must have a final tabstop by default in the end (after semicolon)

VS Code adds the final tab stop if there is not already defined in the snippet. But it doesn't do so if there are no placeholders in the snippet for some reason. I have logged https://github.com/Microsoft/vscode/issues/33761 to track this particular issue.

**Comment by ramya-rao-a** [comment]
@user3323 Revisiting your points again and logging separate issues so that @sergeche doesn't have to wade through this long one

**Using multiple tab stops results in the one defined as ${0} to be ${1}**
Logged #4

**$0 $1 in property name resulting in missing ;**
This is related to your example of `"lsn": "li$0st-st$1yle: none". ` Logged #5

**Double semicolon if one is provided in the snippet**
I have submitted a PR for this. https://github.com/emmetio/stylesheet-formatters/pull/3

** VS Code not adding a final tabstop at the end of the snippet**
Logged https://github.com/Microsoft/vscode/issues/33761. This is fixed in the latest VS Code Insiders now. Please give it a try.

**The snippets.json file should be tolerant towards comments**
Logged https://github.com/Microsoft/vscode/issues/33818

@user3323 That should cover everything. Can you close this current issue?

**Comment by user3323** [comment]
@ramya-rao-a, nice! You are rigorous problem-solver! =)

**Comment by ramya-rao-a** [comment]
Thanks @user3323, and you are rigorous problem-finder :) I appreciate the time you have taken to find these issues and working with us to solve it.
