### ISSUE TITLE
Using multiple tab stops results in the one defined as ${0} to be ${1}

### ISSUE THREAD

**Issue by ramya-rao-a** [emmetio/css-snippets-resolver#4]
Have a snippet like `"lsn": "hello ${0} there${1} ok ${2}"`, the resolved snippet turns out as `hello ${1} there${2} ok ${3}`.

Since `${0}` is the final tab stop as per text mate syntax, it shouldn't be edited by the css-snippets-resolver.

cc @sergeche @user3323

**Comment by ramya-rao-a** [comment]
This happens even without `${0}` in the snippet value

A custom snippet `"lsn": "hello ${1} there${2} ok ${3}"` gets resolved to `hello ${2} there${3} ok ${4}"

**Comment by sergeche** [comment]
Indeed, in most editors `${0}` is a final tabstop. The reason why Emmet upgrades all tabstops to +1 is because of chaining: user can type `c+to` and get:

```css
color: #${1:000};
text-outline: ${1:0} ${2:0} ${3:#000}
```

This results in two `${1}` tabstops which will be connected, same with `${0}`: it’s not possible to have multiple final tabstop. So Emmet automatically upgrades tabstops to:

```css
color: #${2:000};
text-outline: ${3:0} ${4:0} ${5:#000}
```

So all tabstops would be distinct and it’s up to editor to decide which tabstop should be final by using fields model provided by abbreviation expander.

**Comment by ramya-rao-a** [comment]
Agreed
